version: '3.8'

services:
  database:
    container_name: vitnode_postgres_dev_bun
    image: postgres:17.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-root}
      POSTGRES_DB: ${POSTGRES_NAME-vitnode}
    command: ['postgres', '-c', 'log_statement=all'] # log all sql queries
    volumes:
      - ./docker/dev:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - vitnode_dev

  pgadmin:
    container_name: vitnode_pgadmin_dev_bun
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - database
    networks:
      - vitnode_dev

networks:
  vitnode_dev:
