import { routing } from '@/i18n/routing';
import { Metadata } from 'next';
import { hasLocale } from 'next-intl';
import { Geist, Geist_Mono } from 'next/font/google';
import { notFound } from 'next/navigation';
import { RootLayout } from 'vitnode/views/layout/root-layout';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'VitNode',
  description: 'Generated by create next app',
};

export default async function LocaleLayout({
  params,
  ...props
}: Omit<React.ComponentProps<typeof RootLayout>, 'className'>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <RootLayout
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      params={params}
      {...props}
    />
  );
}
